# Generated by Django 4.2.7 on 2023-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('uname', models.CharField(max_length=100)),
                ('ucontact', models.CharField(max_length=10)),
                ('udept', models.CharField(max_length=100)),
            ],
        ),
    ]
