# Generated by Django 4.2.7 on 2023-11-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_important'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
    ]
