# Generated by Django 4.2.7 on 2023-11-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_section_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='important',
            table='important',
        ),
    ]
