# Generated by Django 4.2.7 on 2023-11-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstapp', '0005_delete_important_delete_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='important',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'important',
            },
        ),
    ]
