# Generated by Django 4.2.7 on 2023-11-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
