# Generated by Django 4.2.7 on 2023-11-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
