# Generated by Django 4.2.7 on 2023-11-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='umarks',
            field=models.IntegerField(),
        ),
    ]
