# Generated by Django 4.2.7 on 2023-11-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_user_umarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
