# Generated by Django 4.2.7 on 2023-11-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_user_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('room_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'fees_structure',
            },
        ),
    ]
