# Generated by Django 4.2.7 on 2023-11-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_feesstructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=40)),
                ('uemail', models.EmailField(max_length=254)),
                ('umarks', models.IntegerField()),
                ('room_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'backup',
            },
        ),
    ]
