# Generated by Django 4.2.7 on 2023-11-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_hostelite_delete_backup_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('breakfast', models.CharField(max_length=40)),
                ('lunch', models.CharField(max_length=40)),
                ('dinner', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
