# Generated by Django 5.0.2 on 2024-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('hid', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('room_no', models.CharField(max_length=10)),
                ('complaint_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feid', models.AutoField(primary_key=True, serialize=False)),
                ('hid', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('room_no', models.CharField(max_length=10)),
                ('ques1', models.TextField()),
                ('ques2', models.TextField()),
                ('ques3', models.TextField()),
                ('ques4', models.TextField()),
                ('rating', models.IntegerField()),
                ('suggestions', models.TextField()),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.AddField(
            model_name='hostelite',
            name='password',
            field=models.CharField(default='temp@123', max_length=128),
        ),
    ]
