# Generated by Django 5.0.2 on 2024-04-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_complaint_feedback_hostelite_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelite',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
