# Generated by Django 5.0.2 on 2024-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_alter_hostelite_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ques1',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ques2',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ques3',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ques4',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='feedback',
            name='food_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='food_wrong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='housekeeping_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='housekeeping_wrong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='internet_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='internet_wrong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='maintenance_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='maintenance_wrong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='security_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='security_wrong',
            field=models.BooleanField(default=False),
        ),
    ]
